version: '2'
services:
    tistech-api-app:
        image: tistech-api
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@tistech-api-oracle:1521:TISTECH
            - SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
